package com.accesodatos.AD04;

import com.accesodatos.AD04.entities.Store;
import com.accesodatos.AD04.utilities.DB;
import java.awt.Dimension;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hak
 */
public class StoresDialog extends javax.swing.JDialog {

    DefaultListModel listModel;

    int nStores = 0;

    /**
     * Creates new form CustomersDialog
     *
     * @param parent
     */
    public StoresDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        listModel = new DefaultListModel();
        listStores.setModel(listModel);

        reloadList();
        if (listModel.isEmpty()) {
            lbError.setText("No hay ninguna tienda");
        }
    }

    public void reloadList() {
        removeElements();
        addElements(DB.getStores());
    }

    private void addElements(ArrayList<String> stores) {
        nStores = stores.size();
        for (String store : stores) {
            System.out.println(store);
            listModel.addElement(store);
        }
    }

    private void removeElements() {
        int listLength = nStores;
        if (listLength != 0) {
            for (int i = listLength - 1; i >= 0; i--) {
                listModel.remove(i);
            }
        }
    }

    private void removeSelectedElement() {
        String selectedStore = listStores.getSelectedValue();
        if (selectedStore == null) {
            lbError.setText("Selecciona la tienda a eliminar.");
        } else {
            String[] dataSplit = selectedStore.split(" - ");
            System.out.println("Vamos a borrar la tienda " + selectedStore);
            String[] nameSplit = dataSplit[1].split(", ");
            int respuesta = JOptionPane.showConfirmDialog(null, "Quiere eliminar la tienda \""
                    + nameSplit[0] + "\" de la lista de tiendas?");
            if (respuesta == 0) {

                int idSelectedStore = Integer.valueOf(dataSplit[0]);

                DB.transactionDeleteOfDB(DB.getStore(idSelectedStore));
            }
        }
    }

    private void manageSelectedElement() {
        String selectedStoreString = listStores.getSelectedValue();
        if (selectedStoreString == null) {
            lbError.setText("Selecciona la tienda a gestionar.");
        } else {
            String[] dataSplit = selectedStoreString.split(" - ");
//            System.out.println("Vamos a gestionar la tienda " + selectedStoreString);
//            String[] nameSplit = dataSplit[1].split(", ");
//
//            String nameSelectedStore = dataSplit[1];

            int idSelectedStore = Integer.valueOf(dataSplit[0]);
            
            Store selectedStore = DB.getStore(idSelectedStore);

            StoreItemsOrEmployeesDialog smd = new StoreItemsOrEmployeesDialog(null, true, selectedStore);
            smd.setVisible(true);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbStores = new javax.swing.JLabel();
        btnAddStore = new javax.swing.JButton();
        btnDeleteStore = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listStores = new javax.swing.JList<>();
        lbError = new javax.swing.JLabel();
        btnManageStore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lbStores.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lbStores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStores.setText("Tiendas");

        btnAddStore.setText("Añadir tienda");
        btnAddStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStoreActionPerformed(evt);
            }
        });

        btnDeleteStore.setText("Eliminar tienda");
        btnDeleteStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStoreActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listStores);

        lbError.setForeground(new java.awt.Color(254, 95, 95));
        lbError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btnManageStore.setText("Gestionar tienda");
        btnManageStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbStores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnManageStore, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddStore, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteStore, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbStores, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbError, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteStore, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddStore, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStore, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStoreActionPerformed
        // TODO add your handling code here:
        lbError.setText("");
        StoreCreateDialog scd = new StoreCreateDialog(null, true);
        scd.setVisible(true);
        reloadList();
    }//GEN-LAST:event_btnAddStoreActionPerformed

    private void btnDeleteStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStoreActionPerformed
        // TODO add your handling code here:
        lbError.setText("");
        removeSelectedElement();
        reloadList();
    }//GEN-LAST:event_btnDeleteStoreActionPerformed

    private void btnManageStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStoreActionPerformed
        // TODO add your handling code here:
        lbError.setText("");
        manageSelectedElement();
    }//GEN-LAST:event_btnManageStoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoresDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoresDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoresDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoresDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StoresDialog dialog = new StoresDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStore;
    private javax.swing.JButton btnDeleteStore;
    private javax.swing.JButton btnManageStore;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbError;
    private javax.swing.JLabel lbStores;
    private javax.swing.JList<String> listStores;
    // End of variables declaration//GEN-END:variables
}
