package com.accesodatos.AD04;

import com.accesodatos.AD04.entities.Employee;
import com.accesodatos.AD04.entities.EmployeeStore;
import com.accesodatos.AD04.entities.Store;
import com.accesodatos.AD04.utilities.DB;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hak
 */
public class StoreManageEmployeesDialog extends javax.swing.JDialog {

    DefaultListModel listModel;

    int nEmployees = 0;

    Store selectedStore;
    Employee selectedEmployee;
    
    List<Employee> employees;

    /**
     * Creates new form CustomersDialog
     *
     * @param parent
     */
    public StoreManageEmployeesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public StoreManageEmployeesDialog(java.awt.Frame parent, boolean modal, Store selectedStore) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        listModel = new DefaultListModel();
        listEmployeesStore.setModel(listModel);

        lbSelectedStore.setText(selectedStore.getName());
        this.selectedStore = selectedStore;
        reloadList();
        if (listModel.isEmpty()) {
            lbError.setText("No hay ningún empleado");
        }
    }

    public void reloadList() {
        removeElements();
        employees= DB.getEmployeesStore(selectedStore);
        
        ArrayList<String> employeesWithHours = new ArrayList<>();
        
        employees.forEach((employee) -> {
            String tempEWH = employee.toString() + ". Horas semanales: " + 
                    DB.getEmployeeStore(employee, selectedStore).getHours();
            employeesWithHours.add(tempEWH);
        });
        
        addElements(employeesWithHours);
    }

    private void addElements(ArrayList<String> employees) {
        nEmployees = employees.size();
        for (String employee : employees) {
            System.out.println(employee);
            listModel.addElement(employee);
        }
    }

    private void removeElements() {
        int listLength = nEmployees;
        if (listLength != 0) {
            for (int i = listLength - 1; i >= 0; i--) {
                listModel.remove(i);
            }
        }
    }

    private void removeSelectedElement() {
        String selectedEmployeeString = listEmployeesStore.getSelectedValue();
        if (selectedEmployeeString == null) {
            lbError.setText("Selecciona el producto a eliminar.");
        } else {
            String[] dataSplit = selectedEmployeeString.split(" - ");
            System.out.println("Vamos a eliminar el producto " + selectedEmployeeString);

            int respuesta = JOptionPane.showConfirmDialog(null, "Quiere eliminar el empleado \""
                    + dataSplit[1] + "\" de esta tienda?");
            if (respuesta == 0) {

                int idSelectedEmployee = Integer.valueOf(dataSplit[0]);
                
                selectedEmployee= DB.getEmployee(idSelectedEmployee);
                
                EmployeeStore selectedEmployeeStore = DB.getEmployeeStore(selectedEmployee,selectedStore);
                
                DB.transactionDeleteOfDB(selectedEmployeeStore);

            }
        }
    }

    private void updateHours() {
        String selectedEmployeeString = listEmployeesStore.getSelectedValue();
        if (selectedEmployeeString == null) {
            lbError.setText("Selecciona un empleado.");
        } else {
            String[] dataSplit = selectedEmployeeString.split(" - ");

            int idSelectedEmployee = Integer.valueOf(dataSplit[0]);
            
            selectedEmployee = DB.getEmployee(idSelectedEmployee);

            StoreHoursUpdateDialog shud = new StoreHoursUpdateDialog(null, true, selectedStore, selectedEmployee);
            shud.setVisible(true);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSelectedStore = new javax.swing.JLabel();
        btnAddEmployee = new javax.swing.JButton();
        btnDeleteEmployee = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listEmployeesStore = new javax.swing.JList<>();
        lbError = new javax.swing.JLabel();
        btnUpdateHours = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lbSelectedStore.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lbSelectedStore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSelectedStore.setText("Tienda seleccionada");

        btnAddEmployee.setText("Añadir empleado");
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });

        btnDeleteEmployee.setText("Eliminar empleado");
        btnDeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmployeeActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listEmployeesStore);

        lbError.setForeground(new java.awt.Color(254, 95, 95));
        lbError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btnUpdateHours.setText("Actualizar horas");
        btnUpdateHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateHoursActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSelectedStore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUpdateHours, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSelectedStore, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbError, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateHours, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
        // TODO add your handling code here:
        lbError.setText("");
        StoreEmployeeCreateDialog secd = new StoreEmployeeCreateDialog(null, true, selectedStore);
        secd.setVisible(true);
        reloadList();
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void btnDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmployeeActionPerformed
        // TODO add your handling code here:
        lbError.setText("");
        removeSelectedElement();
        reloadList();
    }//GEN-LAST:event_btnDeleteEmployeeActionPerformed

    private void btnUpdateHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateHoursActionPerformed
        // TODO add your handling code here:
        lbError.setText("");
        updateHours();
        reloadList();
    }//GEN-LAST:event_btnUpdateHoursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreManageEmployeesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreManageEmployeesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreManageEmployeesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreManageEmployeesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StoreManageEmployeesDialog dialog = new StoreManageEmployeesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnDeleteEmployee;
    private javax.swing.JButton btnUpdateHours;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbError;
    private javax.swing.JLabel lbSelectedStore;
    private javax.swing.JList<String> listEmployeesStore;
    // End of variables declaration//GEN-END:variables
}
