/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.accesodatos.AD04;

import com.accesodatos.AD04.utilities.ManageJson;
import com.accesodatos.AD04.utilities.DB;
import com.accesodatos.AD04.utilities.HibernateUtil;
import com.accesodatos.AD04.entities.Provincias;
import com.accesodatos.AD04.entities.Province;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import org.hibernate.Session;
import org.hibernate.query.Query;

/**
 *
 * @author erifc
 */
public class xestionAppMainForm extends javax.swing.JFrame {

    boolean provincesChecked = false;
    private static final String pathProvincias = "/provincias.json";
    private static Provincias provincias = new Provincias();

    public xestionAppMainForm() {
        initComponents();
        this.setLocationRelativeTo(null); //Abrir app en el centro de la pantalla

        if (!provincesChecked) {
            LoadProvinces();
            provincesChecked = true;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        btnEmployees = new javax.swing.JButton();
        btnStores = new javax.swing.JButton();
        btnItems = new javax.swing.JButton();
        btnCustomers = new javax.swing.JButton();
        btnStockReport = new javax.swing.JButton();
        btnTitularesElPais1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("XESTIÓN FRANQUICIA");

        btnEmployees.setText("Empleados");
        btnEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeesActionPerformed(evt);
            }
        });

        btnStores.setText("Tiendas");
        btnStores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoresActionPerformed(evt);
            }
        });

        btnItems.setText("Productos");
        btnItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemsActionPerformed(evt);
            }
        });

        btnCustomers.setText("Clientes");
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });

        btnStockReport.setText("Crear informe stock");
        btnStockReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockReportActionPerformed(evt);
            }
        });

        btnTitularesElPais1.setText("Leer titulares El País");
        btnTitularesElPais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitularesElPais1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStockReport, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(btnStores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTitularesElPais1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(btnCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStores, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnItems, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStockReport, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTitularesElPais1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeesActionPerformed
        // TODO add your handling code here:
        EmployeesDialog ed = new EmployeesDialog(this, true);
        ed.setVisible(true);
    }//GEN-LAST:event_btnEmployeesActionPerformed

    private void btnItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemsActionPerformed
        // TODO add your handling code here:
        ItemsDialog id = new ItemsDialog(this, true);
        id.setVisible(true);
    }//GEN-LAST:event_btnItemsActionPerformed

    private void btnStoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoresActionPerformed
        // TODO add your handling code here:
        StoresDialog sd = new StoresDialog(this, true);
        sd.setVisible(true);
    }//GEN-LAST:event_btnStoresActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        // TODO add your handling code here:
        CustomersDialog cd = new CustomersDialog(this, true);
        cd.setVisible(true);

    }//GEN-LAST:event_btnCustomersActionPerformed

    private void btnStockReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockReportActionPerformed
        // TODO add your handling code here:
        StockReport sr = new StockReport(this, true);
        sr.setVisible(true);
        
    }//GEN-LAST:event_btnStockReportActionPerformed

    private void btnTitularesElPais1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitularesElPais1ActionPerformed
        // TODO add your handling code here:
        ElPaisDialog epd = new ElPaisDialog(this, false);
        epd.setVisible(true);
    }//GEN-LAST:event_btnTitularesElPais1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(xestionAppMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(xestionAppMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(xestionAppMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(xestionAppMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(xestionAppMainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                new xestionAppMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnEmployees;
    private javax.swing.JButton btnItems;
    private javax.swing.JButton btnStockReport;
    private javax.swing.JButton btnStores;
    private javax.swing.JButton btnTitularesElPais1;
    private javax.swing.JLabel lbTitle;
    // End of variables declaration//GEN-END:variables

    //Cargar provincias España
    private void LoadProvinces() {
        //Collemos a sesión de Hibernate
        Session session = HibernateUtil.getSessionFactory().openSession();

        //Facemos unha consulta en HQL
        Query q = session.createQuery("SELECT p FROM Province p");
        List<Province> provincesDB = q.list();
        provincesDB.forEach((province) -> {
            System.out.println(province.toString());
        });

        // jsonToObj devuelvo un Object, para pasarlo a nuestra clase tenemos que hacer así
        ManageJson mj = new ManageJson();
        provincias = Provincias.class.cast(mj.jsonToObj(pathProvincias, Provincias.class));
        System.err.println("prueba contenido provinces");
        LinkedList<Province> listProvincias = provincias.getProvincias();
        Iterator it = listProvincias.iterator();

        while (it.hasNext()) {
            Province tempProvince = (Province) it.next();
//            System.out.println("continene " + tempProvince +"? "+ provincesDB.contains(tempProvince));
            if (!provincesDB.contains(tempProvince)) {
                System.out.println("provincia: " + tempProvince.toString());
                DB.transactionAddToDB(tempProvince);
            }
        }
    }
    
}
